app = "ashraf-map-animator"  # Replace with your desired app name
primary_region = "lax"  # Replace with your preferred region

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static"

[mounts]
  source="your_app_data"
  destination="/data" 